"""
Run the Monte Carlo engine and export the results the interactive HTML
dashboard (dashboard/) needs as a plain JS data file, so the static site has
no runtime dependency on Python or a fetch() call (avoids file:// CORS
issues when opened locally, and needs no build step on Netlify).

Run directly:
    python export_dashboard_data.py
"""

import json

import numpy as np

import config
from analyze import N_SAMPLE_PATHS, SAMPLE_PATH_RATE, sweep_withdrawal_rates
from simulate import run_monte_carlo

OUT_PATH = "dashboard/data.js"


def build_payload() -> dict:
    sweep_df = sweep_withdrawal_rates()

    rng = np.random.default_rng(config.RANDOM_SEED)
    path_result = run_monte_carlo(withdrawal_rate=SAMPLE_PATH_RATE)
    balances = path_result["balances"]
    sample_idx = rng.choice(balances.shape[0], size=N_SAMPLE_PATHS, replace=False)

    # Headline stats: success rate at the classic 4% rule, and the lowest
    # swept rate that still clears a 90% success rate (linear-interpolated).
    four_pct_row = sweep_df.iloc[(sweep_df["withdrawal_rate"] - 0.04).abs().idxmin()]
    above_90 = sweep_df[sweep_df["success_rate"] >= 0.90]
    if not above_90.empty and len(above_90) < len(sweep_df):
        lo = above_90.iloc[-1]
        hi = sweep_df.iloc[above_90.index[-1] + 1]
        frac = (0.90 - lo["success_rate"]) / (hi["success_rate"] - lo["success_rate"])
        safe_rate = lo["withdrawal_rate"] + frac * (hi["withdrawal_rate"] - lo["withdrawal_rate"])
    elif not above_90.empty:
        safe_rate = above_90["withdrawal_rate"].max()
    else:
        safe_rate = None

    payload = {
        "assumptions": {
            "startingPortfolio": config.STARTING_PORTFOLIO,
            "retirementAge": config.RETIREMENT_AGE,
            "horizonYears": config.HORIZON_YEARS,
            "endAge": config.END_AGE,
            "stockAllocation": config.STOCK_ALLOCATION,
            "bondAllocation": config.BOND_ALLOCATION,
            "federalTaxRate": config.FEDERAL_TAX_RATE,
            "rmdStartAge": config.RMD_START_AGE,
            "traditionalFraction": config.TRADITIONAL_FRACTION,
            "rothFraction": config.ROTH_FRACTION,
            "withdrawalSequence": config.WITHDRAWAL_SEQUENCE,
            "inflationRate": config.INFLATION_RATE,
            "nSimulations": config.N_SIMULATIONS,
            "historicalDataStart": config.HISTORICAL_DATA_START,
        },
        "headline": {
            "fourPctWithdrawalRate": round(float(four_pct_row["withdrawal_rate"]), 4),
            "fourPctSuccessRate": round(float(four_pct_row["success_rate"]), 4),
            "safeWithdrawalRate": round(float(safe_rate), 4) if safe_rate is not None else None,
        },
        "successSweep": {
            "withdrawalRates": [round(float(r), 4) for r in sweep_df["withdrawal_rate"]],
            "successRates": [round(float(r), 4) for r in sweep_df["success_rate"]],
        },
        "samplePaths": {
            "withdrawalRate": SAMPLE_PATH_RATE,
            "years": list(range(balances.shape[1])),
            "median": [round(float(v), 2) for v in np.median(balances, axis=0)],
            "p10": [round(float(v), 2) for v in np.percentile(balances, 10, axis=0)],
            "p90": [round(float(v), 2) for v in np.percentile(balances, 90, axis=0)],
            "paths": [[round(float(v), 2) for v in balances[i]] for i in sample_idx],
        },
    }
    return payload


if __name__ == "__main__":
    payload = build_payload()
    with open(OUT_PATH, "w") as f:
        f.write("// Auto-generated by export_dashboard_data.py — do not edit by hand.\n")
        f.write("const DASHBOARD_DATA = ")
        json.dump(payload, f, indent=2)
        f.write(";\n")
    print(f"Wrote {OUT_PATH}")
